### ISSUE TITLE
Importerror:cannot import name Arduino

### ISSUE THREAD

**Issue by lakshaygarg** [thearn/Python-Arduino-Command-API#24]
I am getting this error while compiling the sample code for led given. Everything looks fine. still getting the error. Please help.

**Comment by lakshaygarg** [comment]
@thearn

**Comment by thearn** [comment]
Be sure that you install the library correctly, or run `python setup.py develop` in the top-level of the source directory first.

**Comment by youqingxiaozhua** [comment]
Maybe this package does not support Python 3. I got the same error in Python 3.5, but it works fine with Python 2.7
